### ISSUE TITLE
0.34.0 release appears to be broken

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/pytket-braket#131]
```shell
pip install pytket-braket==0.34.0
```

gives the following error:

```
ERROR: Exception:
Traceback (most recent call last):
  File "/home/alec/tmp/env/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/alec/tmp/env/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "/home/alec/tmp/env/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/home/alec/tmp/env/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 179, in resolve
    self.factory.preparer.prepare_linked_requirements_more(reqs)
  File "/home/alec/tmp/env/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 552, in prepare_linked_requirements_more
    self._complete_partial_requirements(
  File "/home/alec/tmp/env/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 487, in _complete_partial_requirements
    self._prepare_linked_requirement(req, parallel_builds)
  File "/home/alec/tmp/env/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 640, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/home/alec/tmp/env/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 74, in _get_prepared_distribution
    return abstract_dist.get_metadata_distribution()
  File "/home/alec/tmp/env/lib/python3.10/site-packages/pip/_internal/distributions/wheel.py", line 32, in get_metadata_distribution
    return get_wheel_distribution(wheel, canonicalize_name(self.req.name))
  File "/home/alec/tmp/env/lib/python3.10/site-packages/pip/_internal/metadata/__init__.py", line 106, in get_wheel_distribution
    return select_backend().Distribution.from_wheel(wheel, canonical_name)
  File "/home/alec/tmp/env/lib/python3.10/site-packages/pip/_internal/metadata/pkg_resources.py", line 121, in from_wheel
    metadata_dict = {
  File "/home/alec/tmp/env/lib/python3.10/site-packages/pip/_internal/metadata/pkg_resources.py", line 122, in <dictcomp>
    path.split("/", 1)[-1]: read_wheel_metadata_file(zf, path)
  File "/home/alec/tmp/env/lib/python3.10/site-packages/pip/_internal/utils/wheel.py", line 73, in read_wheel_metadata_file
    return source.read(path)
  File "/usr/lib/python3.10/zipfile.py", line 1478, in read
    return fp.read()
  File "/usr/lib/python3.10/zipfile.py", line 913, in read
    buf += self._read1(self.MAX_N)
  File "/usr/lib/python3.10/zipfile.py", line 1003, in _read1
    data = self._decompressor.decompress(data, n)
zlib.error: Error -3 while decompressing data: invalid distance too far back
```

**Comment by cqc-alec** [comment]
Fixed with 0.34.1 (which had no changes, so no idea what caused this).
